const express= require("express");
const cors = require("cors");
const products = require('./Products/Products');
const app = express();
app.use(express.json());
app.use(cors());
app.get("/", (req,res) => res.send( "Welcome")) ;
app.get("/products", (req,res) => res.send( products)) ;
const port =  process.env.port || 4500;
app.listen(port,console.log(`Server is running ${port}`));
